### ISSUE TITLE
Dude.... =)

### ISSUE THREAD

**Issue by lookfirst** [luzzif/bittrex-api-client#1]
Nice job! 

You've got the WS impl. I've got the HTTP impl. LOL

https://github.com/lookfirst/bittrex-typescript

Work together?

**Comment by luzzif** [comment]
Hey man! I'm honored by your consideration of this project (even though it is in a VERY early stage of development), but I want to do this alone since I started coding my own module in order to get better with Node and TypeScript in the first place. Thanks again for the consideration, but I'll kindly refuse for now, I don't feel like I'm "ready".

**Comment by lookfirst** [comment]
LOL. Ok man... you do realize that two brains are always better than one, right? You learn more by working with other people. That's why I reached out. I've been writing code for 20 years and I still think I have something to learn from you. =)
